# -*- coding: utf-8 -*-
"""pandas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HgbjKwH1dtV8daqNnsvScLwFihaEd77E
"""

import pandas as pd

data = {
    'name':['fitsum','solomon','misrak'],
    'age': [23,24,24],
    'gender':['male','male','female']
}

dataframe_01 = pd.DataFrame(data)

print(dataframe_01)

print(dataframe_01.loc[0:1])

print(dataframe_01.loc[0:1])

print(dataframe_01.loc[[0,1]])

print(dataframe_01.loc[[0]])

print(dataframe_01.loc[0])

print(dataframe_01['name'])

print(dataframe_01['age'])

print(dataframe_01['gender'])

df_01 = pd.read_csv("data.csv")

df_01.head()

df_01.to_string()

pd.options.display.max_rows

pd.options.display.max_rows = 9999

df = pd.read_csv("data.csv")

df

json = pd.read_json("https://www.w3schools.com/python/pandas/data.js")

json

json.to_string()

df.head()

df.tail()

df.head(10)

df["Pulse"].head(20)

df.info()

json.info()

df  = pd.read_csv("dirtydata.csv")

df

df_new= df.dropna()

df_new

df.fillna(130, inplace = True)

df.to_string()

df_new

df

df.dropna(inplace = True)

df

df = pd.read_csv("dirtydata.csv")

df

x_mean = df["Calories"].mean()
x_median = df["Calories"].median()
x_mode = df["Calories"].mode()

x_mean

df['Calories'].fillna(x_mean, inplace=True)

df["Calories"]

x_mode

df.info()

df['Calories']

df['Date'] = pd.to_datetime(df['Date'])
df['Date']

df.dropna(subset=['Date'], inplace = True)

df['Date']

df

df.duplicated()

df.drop_duplicates(inplace = True)

df

df_01 = pd.read_csv("data.csv")

df

df_01.info()

df_01.duplicated()

df_01.drop_duplicates(inplace=True)

df_01.duplicated()

df_01.corr()

import matplotlib.pyplot as plt

df_01.plot(kind='scatter', x="Duration", y="Calories")
plt.show()

df_01.plot()
plt.show()

df_01["Duration"].plot(kind="hist")

dict = {
    'orange':[1,2,3,0,1],
    'apple':[3,2,1,0,7]
}

dict

dict_pd = pd.DataFrame(dict)

dict_pd

dict_pd["orange"]

dict_pd['apple']

dict_pd = pd.DataFrame(dict, index=['mehari','fitsum','helen','fasil','seble'])

dict_pd

dict_pd.loc['fitsum']

dict_pd.loc['fasil']

df_01

dict_pd.shape

df_01.shape

df_01 = df_01.append(df_01)

df_01.shape

df_01

df_01.tail()

df_01['Calories'].duplicated()

df_01.drop_duplicates()

df_01.duplicated()

df_01.drop_duplicates(inplace=True)

df_01.shape

df_01.columns

df_01.rename(columns={
    'Duration':'durations',
    'Pulse':'pulses',
    'Maxpulse':'maxpulses',
    'Calories':'calories'
}, inplace=True)

df_01.columns

df_01.isnull().sum()

df_01['calories'].isnull()

df_01['calories'].isnull().sum()

calories_mean = df_01['calories'].mean()

calories_mean

df_01.describe()

df_01.corr()

df_01['calories'].fillna(calories_mean, inplace=True)

df_01.corr()

df_01

df_01.isnull().sum()

df_01.info()

calories = df_01['calories']

type(calories)

calories = df_01[['calories']]

type(calories)



"""loc: is a function which is used to locate the cell by name, where as
iloc: is a function which is used to locate the cell by an index, i denotes the index
"""

df_01

df_01.iloc[0:10]

df_01[df_01['durations']>45].head()

df_01[df_01['pulses']>=110]

df_01.plot(title="Sample Data Graph")

df_01['calories'].plot(kind="box")

df_01['calories'].mean()

df_01['calories'].mode(0)

df_01['calories'].median()

df_01['calories'].max()

df_01['calories'].min()

df_01.index

df_01.columns

df_01.dtypes



from google.colab import drive
drive.mount('/content/drive')



